# Generated by Django 3.1.7 on 2021-03-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_cod', models.CharField(max_length=4, verbose_name='Код')),
                ('color_name', models.CharField(max_length=100, verbose_name='Название')),
                ('color_des', models.TextField(blank=True, default='', verbose_name='Коментарий')),
                ('color_type', models.CharField(blank=True, default='', max_length=10, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['color_cod'],
            },
        ),
        migrations.CreateModel(
            name='Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_num', models.CharField(max_length=2, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
            },
        ),
        migrations.CreateModel(
            name='Izd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izd_cod', models.CharField(default='', max_length=4, verbose_name='Код')),
                ('izd_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Название полностью')),
                ('izd_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок')),
                ('izd_name1', models.CharField(blank=True, default='', max_length=200, verbose_name='Основное название')),
                ('izd_name2', models.CharField(blank=True, default='', max_length=200, verbose_name='Название')),
                ('izd_html', models.TextField(blank=True, default='', verbose_name='Название в HTML')),
                ('izd_des', models.TextField(blank=True, default='', verbose_name='Коментарий')),
                ('izd_col', models.IntegerField(default=1, verbose_name='Количество упаковок')),
                ('izd_up', models.ManyToManyField(blank=True, to='shema.Up', verbose_name='Виды упаковоковок')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
    ]
