# Generated by Django 3.1.7 on 2021-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shema', '0002_auto_20210310_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izd_title', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('izd_name1', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('izd_name2', models.CharField(default='', max_length=100, verbose_name='Модуль')),
            ],
        ),
        migrations.AddField(
            model_name='izd',
            name='name_block',
            field=models.ManyToManyField(blank=True, to='shema.NameBlock', verbose_name='Изделие'),
        ),
    ]
