# Generated by Django 3.1.7 on 2021-03-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shema', '0004_auto_20210310_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameblock',
            name='izd',
        ),
        migrations.AddField(
            model_name='nameblock',
            name='izd',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='shema.izd', verbose_name='Изделие'),
        ),
    ]
