# Generated by Django 3.1.7 on 2021-03-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shema', '0005_auto_20210310_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameblock',
            name='izd',
        ),
        migrations.AddField(
            model_name='izd',
            name='izd_name_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shema.nameblock'),
        ),
    ]
