# Generated by Django 3.1.7 on 2021-03-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shema', '0008_remove_izd_izd_name_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameBlock',
        ),
        migrations.AddField(
            model_name='izd',
            name='izd_modul',
            field=models.CharField(default='', max_length=100, verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='izd',
            name='izd_title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='izd',
            name='izd_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
    ]
