# Generated by Django 3.1.7 on 2021-03-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shema', '0009_auto_20210311_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='up',
            name='izd_modul',
            field=models.CharField(default='', max_length=100, verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='up',
            name='izd_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='up',
            name='izd_title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
        ),
    ]
