# Generated by Django 3.1.7 on 2021-03-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shema', '0011_auto_20210311_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='izd',
            old_name='izd_modu2',
            new_name='izd_name2',
        ),
        migrations.RenameField(
            model_name='up',
            old_name='izd_modu2',
            new_name='izd_name2',
        ),
    ]
